server:
    port: 8090
resilience4j.ratelimiter:
    instances:
        fluffyRateLimiter:
            limitForPeriod: 5
            limitRefreshPeriod: 10s
            timeoutDuration: 0
resilience4j.timelimiter:
    instances:
        fluffyTimeLimiter:
            timeoutDuration: 2s
            cancelRunningFuture: true
resilience4j.retry:
    instances:
        fluffyRetry:
            maxAttempts: 3
            waitDuration: 2s

