server:
    port: 8090

management:
    security:
        enabled: false
    endpoints:
        web:
            exposure:
                include: "*"
    health:
        circuitbreakers:
            enabled: true
        ratelimiters:
            enabled: true
    endpoint:
        health:
            show-details: always


resilience4j.ratelimiter:
    instances:
        fluffyRateLimiter:
            registerHealthIndicator: true
            limitForPeriod: 5
            limitRefreshPeriod: 15s
            timeoutDuration: 0

resilience4j.timelimiter:
    instances:
        fluffyTimeLimiter:
            timeoutDuration: 2s
            cancelRunningFuture: false

resilience4j.retry:
    instances:
        fluffyRetry:
            maxAttempts: 3
            waitDuration: 2s

resilience4j.circuitbreaker:
    instances:
        fluffyCircuitBreaker:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 5
            slidingWindowType: COUNT_BASED #default
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 30s
            failureRateThreshold: 80

resilience4j.bulkhead:
    instances:
        fluffyBulkhead:
            maxConcurrentCalls: 1

resilience4j.thread-pool-bulkhead:
    instances:
        fluffyBulkheadThreaded:
            maxThreadPoolSize: 1
            coreThreadPoolSize: 1
            queueCapacity: 1
